# pull official base image
FROM python:3.11.4-slim-buster

WORKDIR /src

# install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends netcat
RUN pip install --upgrade pip
COPY ./requirements .
RUN pip install -r ./prod.txt

# copy project
COPY . /src

# run entrypoint.prod.sh
ENTRYPOINT ["/src/entrypoint.prod.sh"]
